spring:
  application:
    name: credit-card-management

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/freePDB1
    username: system
    password: MyNewPassword123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 7072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
 env:
  enabled: true
  info:
   app: 
    name: CreditCard MS
    description: CreditCard microservice
    version: 1.0.0
    author: Tasmiya
    location: bangalore
    projectno: batch14

logging:
  level:
       com.ofss: INFO
  file:
       name: logs/credit-card-management.log
  logback:
       rollingpolicy:
         max-file-size: 10MB
         max-history: 7