spring.application.name=merchant-management
server.port=7073

# Eureka
eureka.client.service-url.defaultZone=http://localhost:7070/eureka/

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1
spring.datasource.username=system
spring.datasource.password=jithu123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Application Info
info.app.name=Merchant
info.app.description=Merchant Microservice
info.app.version=1.0.0
info.app.author=ayushman
info.app.location=pune
info.app.projectno=credit_card_management